### ISSUE TITLE
PostCSS relative urls for npm installed dependencies not resolving.

### ISSUE THREAD

**Issue by CxRes** [Anidetrix/rollup-plugin-styles#132]
I am including @mdi/fonts (installed from npm) like so:

```js
import '@mdi/font/css/materialdesignicons.css';
```

This file contains the following `@font-face` declaration
```css
@font-face {
  font-family: "Material Design Icons";
  src: url("../fonts/materialdesignicons-webfont.eot?v=5.3.45");
  src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=5.3.45") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=5.3.45") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=5.3.45") format("truetype");
  font-weight: normal;
  font-style: normal;
}
``` 

I get the following error when bundling:
```sh
Unresolved URL `../fonts/materialdesignicons-webfont.eot?v=5.3.45` in `src: url("../fonts/materialdesignicons-webfont.eot?v=5.3.45")`
Unresolved URL `../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45` in `src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=5.3.45") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=5.3.45") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=5.3.45") format("truetype")`
Unresolved URL `../fonts/materialdesignicons-webfont.woff2?v=5.3.45` in `src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=5.3.45") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=5.3.45") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=5.3.45") format("truetype")`
Unresolved URL `../fonts/materialdesignicons-webfont.woff?v=5.3.45` in `src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=5.3.45") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=5.3.45") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=5.3.45") format("truetype")`Unresolved URL `../fonts/materialdesignicons-webfont.ttf?v=5.3.45` in `src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=5.3.45") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=5.3.45") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=5.3.45") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=5.3.45") format("truetype")` 
```

Now, I do not get an error for other asset files that I include directly from `node_modules` in my css. Something like `src: url('fontsource-roboto/files/roboto-latin-400-normal.woff2') format('woff2')` is bundled just fine.

I presume this is occurring because all relative paths are being resolved from `'.'` and not `/node_modules/@mdi/font`.

**Comment by Anidetrix** [comment]
Hi @CxRes,

Seems like a querystring issue, will fix.

**Comment by art-solopov** [comment]
I think I'm having a similar problem with [boxicons.](https://github.com/atisawd/boxicons/blob/master/css/boxicons.css)

Instead of proper path I get a bunch of relative paths in the output:

```css
@font-face
{
    font-family: 'boxicons';
    font-weight: normal;
    font-style: normal;

    src: url('./boxicons-98d6f327.eot');
    src: url('./boxicons-98d6f327.eot') format('embedded-opentype'),
    url('./boxicons-6509f2c1.woff2') format('woff2'),
    url('./boxicons-fbd1d20f.woff') format('woff'),
    url('./boxicons-614af3c9.ttf') format('truetype'),
    url('./boxicons-1ba25a8d.svg#boxicons') format('svg');
}

```
