### ISSUE TITLE
scss import call does not work with aliases that has special characters

### ISSUE THREAD

**Issue by parttee** [Anidetrix/rollup-plugin-styles#154]
If I create an alias for root folder in the config object and set it to some special character, then the alias does not work in the scss import call but works f.e. in background image. 
 
```js
/* config */
styles({
  ...
  alias: {
    '@': path.join(__dirname),
  }
})
```

and my folder structure is something like
scss/
images/
foo/

```scss
/* foo/style.scss */
@import "@/scss/mixins"; /* does not work */

.foo {
  background: url("@/images/foo.png"); /* for some reason this still works */
}
```

Everything works if I create separate aliases for scss and images folders, like
```js
styles({
  ...
  alias: {
    'scss': path.join(__dirname, 'scss'),
    'images': path.join(__dirname, 'images'),
  }
})
```
