### ISSUE TITLE
Duplicate emitted files when multiple `url()` references to same file

### ISSUE THREAD

**Issue by taylor-hunt-kr** [Anidetrix/rollup-plugin-styles#170]
Some CSS like this:

```css
.thing {
  position: absolute;
  top: 0; left: 0; right: 0; bottom: 0;
  background-image: url("./img/wire.png"), url("./img/wire.png");
  background-repeat: no-repeat, no-repeat;
  background-position: 33% 0, 66% 0;
  background-size: 11px 56px, 11px 56px;
}
```

…produces the following Rollup warning:

> (!) The emitted file "wire-9d64d534.png" overwrites a previously emitted file of the same name.

While nothing breaks, processing `url()` assets only once each seems like a good possible improvement.
