### ISSUE TITLE
Prevent to add hash to referenced files inside CSS

### ISSUE THREAD

**Issue by stefanobartoletti** [Anidetrix/rollup-plugin-styles#223]
I'm trying to correclty import a SVG inside a CSS file, this is what I'm doing in my source file:

```css
ul {
  list-style-image: url('../img/check.svg');
}
```
and this is what I get as a output:

```css
ul {
  list-style-image: url("./check-0ecf99f0.svg");
}
```

I need to reference the file without the hash, just by its simple name `check.svg`, how can I correctly do so?
