### ISSUE TITLE
`preserveModules`, but keep and entry point with `@import`

### ISSUE THREAD

**Issue by fregante** [Anidetrix/rollup-plugin-styles#248]
I'm trying to use `preserveModules: true` primarily for JS code, but this has a confusing output for CSS files.

### Input

```js
/* main.js */
import './alpha.css';
import './beta.css';
console.log('hi')
```

```css
/* alpha.css */
html {color: red;}
```

```css
/* beta.css */
body {font-weight: bold}
```

## Current output

```js
/* main.js */
console.log('hi')
```

```js
/* main.css */
html {color: red;}
body {font-weight: bold}
```

```css
/* alpha.css */
html {color: red;}
```

```css
/* beta.css */
body {font-weight: bold}
```

## Expected output

One of:

- _only_ `main.css` (ignoring `preserveModule`, which I don't need for CSS)
- `alpha.css`, `beta.css`, and a `main.css` that looks like `@import 'alpha.css';@import 'beta.css'`

## Final notes

I'm mostly ok with the current behavior as the duplicate CSS is minor and inert, but I'm afraid that this is considered a "bug" and it might be "fixed" in a way that doesn't match my expectations (i.e. `main.css` is no longer created or it's empty, without imports)

## Related

- https://github.com/Anidetrix/rollup-plugin-styles/issues/130
